language: python
python:
  - 2.7
# command to install dependencies
install:
  - pip install -r requirements.txt
  - python setup.py develop
# command to run tests
script:
  - py.test
after_success:
  - codecov --token=26f8deeb-b9ed-4c4c-a51a-6a18da301e6b
  - coveralls
